export const topcollection = [
    {
        "id": 1,
        "title": "Azuki",
        "image": require('./images/collectionCard/azuki.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 2,
        "title": "Crypto Punk",
        "image": require('./images/collectionCard/2.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 3,
        "title": "Doodles",
        "image": require('./images/collectionCard/3.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 4,
        "title": "Clones",
        "image": require('./images/collectionCard/4.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 5,
        "title": "Bored Ape Yacht",
        "image": require('./images/collectionCard/5.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 6,
        "title": "Hape Prime",
        "image": require('./images/collectionCard/6.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 7,
        "title": "Killer",
        "image": require('./images/collectionCard/7.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 8,
        "title": "The Sandbox",
        "image": require('./images/collectionCard/8.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 9,
        "title": "Zypcy's Supernormal",
        "image": require('./images/collectionCard/9.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 10,
        "title": "Bored Ape Kannel",
        "image": require('./images/collectionCard/10.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 11,
        "title": "Lives of Asuna",
        "image": require('./images/collectionCard/11.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 12,
        "title": "Hyperbears Club",
        "image": require('./images/collectionCard/12.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 13,
        "title": "Turbo",
        "image": require('./images/collectionCard/13.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 14,
        "title": "Big Hero",
        "image": require('./images/collectionCard/14.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
    {
        "id": 15,
        "title": "Ghost",
        "image": require('./images/collectionCard/15.png'),
        "volume": "34,00.47",
        "percent7h": "-68.94%",
        "percent24h": "+68.94%",
        "floorPrice": "7.3",
        "owners": "6.3k",
        "items": "10.3k",

    },
];


export const artscollection = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/art/art1.png'),
        "profileimage": require('./images/collections/art/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/art/art2.png'),
        "profileimage": require('./images/collections/art/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/art/art3.png'),
        "profileimage": require('./images/collections/art/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/art/art4.png'),
        "profileimage": require('./images/collections/art/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/art/art5.png'),
        "profileimage": require('./images/collections/art/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/art/art6.png'),
        "profileimage": require('./images/collections/art/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]

export const domainnames = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/domainnames/domainname1.png'),
        "profileimage": require('./images/collections/domainnames/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/domainnames/domainname2.png'),
        "profileimage": require('./images/collections/domainnames/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/domainnames/domainname3.png'),
        "profileimage": require('./images/collections/domainnames/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/domainnames/domainname4.png'),
        "profileimage": require('./images/collections/domainnames/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/domainnames/domainname5.png'),
        "profileimage": require('./images/collections/domainnames/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/domainnames/domainname6.png'),
        "profileimage": require('./images/collections/domainnames/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]

export const musiccollection = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/music/music1.png'),
        "profileimage": require('./images/collections/music/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/music/music2.png'),
        "profileimage": require('./images/collections/music/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/music/music3.png'),
        "profileimage": require('./images/collections/music/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/music/music4.png'),
        "profileimage": require('./images/collections/music/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/music/music5.png'),
        "profileimage": require('./images/collections/music/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/music/music6.png'),
        "profileimage": require('./images/collections/music/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]

export const collectiblescollection = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/collectibles/collectibles1.png'),
        "profileimage": require('./images/collections/collectibles/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/collectibles/collectibles2.png'),
        "profileimage": require('./images/collections/collectibles/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/collectibles/collectibles3.png'),
        "profileimage": require('./images/collections/collectibles/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/collectibles/collectibles4.png'),
        "profileimage": require('./images/collections/collectibles/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/collectibles/collectibles5.png'),
        "profileimage": require('./images/collections/collectibles/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/collectibles/collectibles6.png'),
        "profileimage": require('./images/collections/collectibles/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]



export const photographycollection = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/photography/photography1.png'),
        "profileimage": require('./images/collections/photography/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/photography/photography2.png'),
        "profileimage": require('./images/collections/photography/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/photography/photography3.png'),
        "profileimage": require('./images/collections/photography/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/photography/photography4.png'),
        "profileimage": require('./images/collections/photography/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/photography/photography5.png'),
        "profileimage": require('./images/collections/photography/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/photography/photography6.png'),
        "profileimage": require('./images/collections/photography/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]


export const virtualworlds = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/virtualworlds/virtualworlds1.png'),
        "profileimage": require('./images/collections/virtualworlds/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/virtualworlds/virtualworlds2.png'),
        "profileimage": require('./images/collections/virtualworlds/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/virtualworlds/virtualworlds3.png'),
        "profileimage": require('./images/collections/virtualworlds/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/virtualworlds/virtualworlds4.png'),
        "profileimage": require('./images/collections/virtualworlds/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/virtualworlds/virtualworlds5.png'),
        "profileimage": require('./images/collections/virtualworlds/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/virtualworlds/virtualworlds6.png'),
        "profileimage": require('./images/collections/virtualworlds/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]


export const sportscollection = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/sports/sports1.png'),
        "profileimage": require('./images/collections/sports/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/sports/sports2.png'),
        "profileimage": require('./images/collections/sports/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/sports/sports3.png'),
        "profileimage": require('./images/collections/sports/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/sports/sports4.png'),
        "profileimage": require('./images/collections/sports/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/sports/sports5.png'),
        "profileimage": require('./images/collections/sports/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/sports/sports6.png'),
        "profileimage": require('./images/collections/sports/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]



export const tradingcards = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/tradingcards/tradingcard1.png'),
        "profileimage": require('./images/collections/tradingcards/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/tradingcards/tradingcard2.png'),
        "profileimage": require('./images/collections/tradingcards/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/tradingcards/tradingcard3.png'),
        "profileimage": require('./images/collections/tradingcards/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/tradingcards/tradingcard4.png'),
        "profileimage": require('./images/collections/tradingcards/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/tradingcards/tradingcard5.png'),
        "profileimage": require('./images/collections/tradingcards/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/tradingcards/tradingcard6.png'),
        "profileimage": require('./images/collections/tradingcards/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]


export const utilitycollection = [
    {
        "id": 1,
        "title": "Mehtew Official",
        "image": require('./images/collections/utility/utility1.png'),
        "profileimage": require('./images/collections/utility/profileimage1.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 2,
        "title": "Mehtew Official",
        "image": require('./images/collections/utility/utility2.png'),
        "profileimage": require('./images/collections/utility/profileimage2.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 3,
        "title": "Mehtew Official",
        "image": require('./images/collections/utility/utility3.png'),
        "profileimage": require('./images/collections/utility/profileimage3.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 4,
        "title": "Mehtew Official",
        "image": require('./images/collections/utility/utility4.png'),
        "profileimage": require('./images/collections/utility/profileimage4.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 5,
        "title": "Mehtew Official",
        "image": require('./images/collections/utility/utility5.png'),
        "profileimage": require('./images/collections/utility/profileimage5.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
    {
        "id": 6,
        "title": "Mehtew Official",
        "image": require('./images/collections/utility/utility6.png'),
        "profileimage": require('./images/collections/utility/profileimage6.png'),
        "by": "gfzyk",
        "description":"o Josie to JOY, browse and trade NFTs from some of the world's top crypto artists on Op",
    },
]
